### ISSUE TITLE
goimports not working

### ISSUE THREAD

**Issue by Broyojo** [micro-editor/go-plugin#8]
When I am saving my code, it is not automatically importing packages.

**Comment by Broyojo** [comment]
I have goimports in my path so I do not know why it is not working. gofmt is in my path and it works fine.

**Comment by zyedidia** [comment]
Have you enabled it by turning on the `go.goimports` option?

**Comment by Broyojo** [comment]
How do you do that exactly? I am new to micro so I do not know a lot.

**Comment by zyedidia** [comment]
No problem, just run `> set go.goimports true` (press ctrl-e for the `> ` prompt and type the command in).

**Comment by Broyojo** [comment]
oh nice it works now, thanks!
